export const errorCodes = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TOKEN_EXPIRES: "TOKEN_EXPIRES",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_ALREADY_REGISTERED: "EVENT_ALREADY_REGISTERED",
  EVENT_REGISTRATION_CLOSED: "EVENT_REGISTRATION_CLOSED",
  BAD_REQUEST: "BAD_REQUEST"
};